// Generated by Grafana k6 Studio (1.8.0) on 2025-10-29T17:52:09.343Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/stats`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/workouts`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/workouts`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        "if-none-match": `"0ab76f11851428857d17149e7d22db4b6002b5c1"`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/workouts`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        "if-none-match": `"0ab76f11851428857d17149e7d22db4b6002b5c1"`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/stats`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        "if-none-match": `"0ab76f11851428857d17149e7d22db4b6002b5c1"`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/workouts`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        "if-none-match": `"0ab76f11851428857d17149e7d22db4b6002b5c1"`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/stats`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        "if-none-match": `"0ab76f11851428857d17149e7d22db4b6002b5c1"`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/workouts`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "sec-ch-ua": `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        accept: `*/*`,
        origin: `https://fitness-zqx3.onrender.com`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://fitness-zqx3.onrender.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `es-419,es;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://fitness-zqx3.onrender.com/api/workouts`;
    resp = http.request(
      "POST",
      url,
      `{"name":"Cardio","type":"sports","duration":60,"calories":300,"location":null,"image":null}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
