# Nombre que aparecerá en la pestaña "Actions"
name: Prueba de Carga K6

# Define cuándo debe ejecutarse el workflow
on:
  # Se ejecuta cada vez que haces push a la rama 'main'
  push:
    branches: [ main ]
    
  # Permite ejecutarlo manualmente desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tu código (para que GitHub tenga tu script de K6)
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Instala K6 en la máquina virtual de GitHub
      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      # 3. Ejecutar K6 y ENVIAR resultados a InfluxDB
      - name: Run k6 load test
        # Define las variables de entorno que K6 leerá automáticamente
        env:
          K6_INFLUXDB_ORGANIZATION: ${{ secrets.INFLUXDB_ORG }}
          K6_INFLUXDB_BUCKET: ${{ secrets.INFLUXDB_BUCKET }}
          K6_INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
        run: |
          # El comando --out ahora solo necesita la URL de InfluxDB
          k6 run --out "influxdb=${{ secrets.INFLUXDB_URL }}" k6-script.js
